"use client";

// Event model
export type TEvent = {
  id: string;
  title: string;
  imageUrl: string;
  location: string;
  date: string;
  status: "upcoming" | "live" | "past";
  price: number;
  category: string;
};

const categories = ["Semua", "Workshop", "Sosial", "Webinar", "Kompetisi"];
const tabs = ["Semua", "Mendatang", "Berlangsung", "Selesai"];
const EVENTS_PER_PAGE = 6;

export const EVENTS_DUMMY: TEvent[] = [
  {
    id: "1",
    title: "Workshop Design Thinking",
    imageUrl: "/images/event.jpg",
    location: "Jakarta",
    date: "2025-06-10T09:00:00Z",
    status: "upcoming",
    price: 0,
    category: "Workshop",
  },
  {
    id: "2",
    title: "Aksi Sosial di Bandung",
    imageUrl: "/images/event.jpg",
    location: "Bandung",
    date: "2025-06-12T08:00:00Z",
    status: "live",
    price: 10000,
    category: "Sosial",
  },
  {
    id: "3",
    title: "Webinar UI/UX Modern",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-05T10:00:00Z",
    status: "past",
    price: 0,
    category: "Webinar",
  },
  {
    id: "4",
    title: "Kompetisi Coding Nasional",
    imageUrl: "/images/event.jpg",
    location: "Surabaya",
    date: "2025-06-15T09:00:00Z",
    status: "upcoming",
    price: 25000,
    category: "Kompetisi",
  },
  {
    id: "5",
    title: "Webinar Public Speaking",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-18T13:00:00Z",
    status: "upcoming",
    price: 0,
    category: "Webinar",
  },
  {
    id: "6",
    title: "Sosialisasi Pengelolaan Sampah",
    imageUrl: "/images/event.jpg",
    location: "Yogyakarta",
    date: "2025-06-08T09:00:00Z",
    status: "live",
    price: 0,
    category: "Sosial",
  },
  {
    id: "7",
    title: "Kompetisi Esai Pemuda",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-03T15:00:00Z",
    status: "past",
    price: 5000,
    category: "Kompetisi",
  },
  {
    id: "8",
    title: "Workshop Pemrograman Dasar",
    imageUrl: "/images/event.jpg",
    location: "Malang",
    date: "2025-06-14T09:00:00Z",
    status: "upcoming",
    price: 20000,
    category: "Workshop",
  },
  {
    id: "9",
    title: "Webinar Manajemen Waktu",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-11T11:00:00Z",
    status: "live",
    price: 0,
    category: "Webinar",
  },
  {
    id: "10",
    title: "Sosialisasi Edukasi Kesehatan",
    imageUrl: "/images/event.jpg",
    location: "Depok",
    date: "2025-06-04T08:00:00Z",
    status: "past",
    price: 0,
    category: "Sosial",
  },
  {
    id: "11",
    title: "Workshop Figma UI",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-19T10:00:00Z",
    status: "upcoming",
    price: 0,
    category: "Workshop",
  },
  {
    id: "12",
    title: "Kompetisi Desain Poster",
    imageUrl: "/images/event.jpg",
    location: "Bandung",
    date: "2025-06-06T14:00:00Z",
    status: "past",
    price: 10000,
    category: "Kompetisi",
  },
  {
    id: "13",
    title: "Webinar Soft Skill Mahasiswa",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-13T10:00:00Z",
    status: "upcoming",
    price: 0,
    category: "Webinar",
  },
  {
    id: "14",
    title: "Pelatihan Kewirausahaan Sosial",
    imageUrl: "/images/event.jpg",
    location: "Jakarta",
    date: "2025-06-07T09:00:00Z",
    status: "live",
    price: 15000,
    category: "Workshop",
  },
  {
    id: "15",
    title: "Pentas Seni Komunitas",
    imageUrl: "/images/event.jpg",
    location: "Semarang",
    date: "2025-06-09T18:00:00Z",
    status: "upcoming",
    price: 5000,
    category: "Sosial",
  },
  {
    id: "16",
    title: "Webinar Literasi Digital",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-17T10:00:00Z",
    status: "upcoming",
    price: 0,
    category: "Webinar",
  },
  {
    id: "17",
    title: "Kompetisi Video Kreatif",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-05T16:00:00Z",
    status: "past",
    price: 10000,
    category: "Kompetisi",
  },
  {
    id: "18",
    title: "Workshop Public Relation",
    imageUrl: "/images/event.jpg",
    location: "Surabaya",
    date: "2025-06-20T09:00:00Z",
    status: "upcoming",
    price: 0,
    category: "Workshop",
  },
  {
    id: "19",
    title: "Sosialisasi Lingkungan Sehat",
    imageUrl: "/images/event.jpg",
    location: "Tangerang",
    date: "2025-06-02T08:30:00Z",
    status: "past",
    price: 0,
    category: "Sosial",
  },
  {
    id: "20",
    title: "Webinar Karier Remaja",
    imageUrl: "/images/event.jpg",
    location: "Online",
    date: "2025-06-16T13:00:00Z",
    status: "upcoming",
    price: 0,
    category: "Webinar",
  },
];
