export const DUMMY_PRODUCTS = [
  {
    id: "p1",
    name: "Kaos Komunitas",
    imageUrl: "/images/event.jpg",
    price: 125000,
    sold: 500,
    rating: 4.8,
    discount: 10,
  },
  {
    id: "p2",
    name: "Totebag Aksi Sosial",
    imageUrl: "/images/event.jpg",
    price: 95000,
    sold: 100,
    rating: 4.7,
    discount: 0,
  },
  {
    id: "p3",
    name: "Stiker Dukungan",
    imageUrl: "/images/event.jpg",
    price: 20000,
    sold: 1000,
    rating: 4.9,
    discount: 25,
  },
  {
    id: "p4",
    name: "Kaos Komunitas",
    imageUrl: "/images/event.jpg",
    price: 125000,
    sold: 500,
    rating: 4.8,
    discount: 10,
  },
  {
    id: "p5",
    name: "Totebag Aksi Sosial",
    imageUrl: "/images/event.jpg",
    price: 95000,
    sold: 100,
    rating: 4.7,
    discount: 0,
  },
  {
    id: "p6",
    name: "Stiker Dukungan",
    imageUrl: "/images/event.jpg",
    price: 20000,
    sold: 1000,
    rating: 4.9,
    discount: 25,
  },
  {
    id: "p7",
    name: "Mug Komunitas",
    imageUrl: "/images/event.jpg",
    price: 50000,
    sold: 300,
    rating: 4.6,
    discount: 5,
  },
  {
    id: "p8",
    name: "Topi Aksi Sosial",
    imageUrl: "/images/event.jpg",
    price: 75000,
    sold: 200,
    rating: 4.5,
    discount: 15,
  },
  {
    id: "p9",
    name: "Gantungan Kunci",
    imageUrl: "/images/event.jpg",
    price: 15000,
    sold: 800,
    rating: 4.8,
    discount: 0,
  },
  {
    id: "p10",
    name: "Poster Dukungan",
    imageUrl: "/images/event.jpg",
    price: 30000,
    sold: 400,
    rating: 4.7,
    discount: 20,
  },
  {
    id: "p11",
    name: "Kaos Premium",
    imageUrl: "/images/event.jpg",
    price: 150000,
    sold: 250,
    rating: 4.9,
    discount: 10,
  },
  {
    id: "p12",
    name: "Tas Ransel",
    imageUrl: "/images/event.jpg",
    price: 200000,
    sold: 150,
    rating: 4.6,
    discount: 5,
  },
  {
    id: "p13",
    name: "Notebook Komunitas",
    imageUrl: "/images/event.jpg",
    price: 45000,
    sold: 600,
    rating: 4.8,
    discount: 0,
  },
  {
    id: "p14",
    name: "Pin Dukungan",
    imageUrl: "/images/event.jpg",
    price: 10000,
    sold: 1200,
    rating: 4.9,
    discount: 30,
  },
  {
    id: "p15",
    name: "Sweater Komunitas",
    imageUrl: "/images/event.jpg",
    price: 250000,
    sold: 100,
    rating: 4.7,
    discount: 10,
  },
  {
    id: "p16",
    name: "Bantal Dukungan",
    imageUrl: "/images/event.jpg",
    price: 80000,
    sold: 350,
    rating: 4.6,
    discount: 5,
  },
  {
    id: "p17",
    name: "Kalender Komunitas",
    imageUrl: "/images/event.jpg",
    price: 30000,
    sold: 500,
    rating: 4.8,
    discount: 0,
  },
  {
    id: "p18",
    name: "Tumbler Aksi Sosial",
    imageUrl: "/images/event.jpg",
    price: 100000,
    sold: 200,
    rating: 4.7,
    discount: 15,
  },
  {
    id: "p19",
    name: "Poster Premium",
    imageUrl: "/images/event.jpg",
    price: 50000,
    sold: 400,
    rating: 4.9,
    discount: 20,
  },
  {
    id: "p20",
    name: "Sticker Pack",
    imageUrl: "/images/event.jpg",
    price: 25000,
    sold: 1000,
    rating: 4.8,
    discount: 25,
  },
];